---

- name: Activate current account for ansible
  command: gcloud auth activate-service-account --key-file {{ secrets.project.service_account }} --project={{ secrets.project.name }} 

- name: Create cloud composer environment
  shell: "gcloud composer environments create {{ services.composer.name }} \
    --location {{ secrets.project.region }} \
    --zone {{ secrets.project.zone }} \
    --machine-type {{ services.composer.machine }} \
    --disk-size {{ services.composer.disk }} \
    --node-count {{ services.composer.nodes }} \
    --python-version {{ services.composer.python_version }}"

