---
- name: Github user email
  command: git config --global user.email {{ secrets.git.email }}

- name: Github user name
  command: git config --global user.name {{ secrets.git.name }}

- name: Github user email
  command: git config --global user.email {{ secrets.git.email }}

- name: Github merge tool
  command: git config --global merge.tool vimdiff

- name: Copy pre-commit hook
  copy:
    src: "{{ role_path }}/templates/pre-commit.sh"
    dest: ../../../base/.git/hooks/pre-commit
    mode: a+x