---

- name: Activate current account for ansible
  command: gcloud auth activate-service-account --key-file {{ secrets.project.service_account }} --project={{ secrets.project.name }} 

- name: Create backend kubernetes environment
  shell: "gcloud container clusters create {{ services.kubernetes.name }} \
    --zone {{ secrets.project.zone }} \
    --machine-type {{ services.kubernetes.machine }} \
    --image-type {{ services.kubernetes.image }} \
    --accelerator type={{ services.kubernetes.gpu_type }},count={{ services.kubernetes.gpu_count }} \
    --disk-size {{ services.kubernetes.disk }} \
    --disk-type {{ services.kubernetes.disk_type }} \
    --num-nodes {{ services.kubernetes.nodes }} \
    --min-nodes {{ services.kubernetes.min_nodes }} \
    --max-nodes {{ services.kubernetes.max_nodes }} \
    --enable-autorepair \
    --enable-autoupgrade \
    --enable-autoscaling"


# TODO Create node for frontend

- name: Install drivers
  command: kubectl apply -f https://raw.githubusercontent.com/GoogleCloudPlatform/container-engine-accelerators/master/nvidia-driver-installer/ubuntu/daemonset-preloaded.yaml

- name: Generate credentials
  command: gcloud container clusters get-credentials "{{ services.kubernetes.name }}" --region {{ secrets.project.zone }} --project {{ secrets.project.name }} 

- name: Register output nodes
  command: kubectl get nodes -o wide
  register: node_config

- name: Register output cluster
  command: gcloud container clusters list
  register: cluster_config

- name: Cluster configs
  debug: var=cluster_config.stdout_lines

- name: Node configs
  debug: var=node_config.stdout_lines
