---

- name: Update and upgrade apt packages for kubectl
  apt:
    upgrade: yes
    update_cache: no

- name: aptkey
  shell: curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -

- name: Echo
  shell: echo "deb https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee -a /etc/apt/sources.list.d/kubernetes.list

- name: Update and upgrade apt packages
  apt:
    upgrade: yes
    update_cache: no

- name: Install kubectl
  shell: sudo apt-get install -y kubectl #snap for 20.04

- name: Register output version
  command: kubectl version --client
  register: version

- name: kubectl version
  debug: var=version.stdout_lines
