---
- name: Install required applications
  hosts: localhost
  connection: local
  become: true  # This means that all tasks will be executed with sudo
  vars_files:
    - /home/ubuntu/.secrets/secrets.yaml
    - vars/main.yml
  roles:
    # - gcp-cloud-composer
    # - gcp-kubernetes
    #- local-docker
    #- local-kubectl
    #- local-skaffold
    #- local-minikube
    - local-miniconda
    #- local-kubeflow
