---
- name: Install required applications
  hosts: localhost
  connection: local
  become: true  # This means that all tasks will be executed with sudo
  vars_files:
    - ../vault/vault.yml
  roles:
    #- file-permissions
    - git
    #- google-cloud