---

## miniconda: https://docs.conda.io/projects/conda/en/latest/user-guide/install/rpm-debian.html

- name: Install our public GPG key to trusted store
  shell: curl https://repo.anaconda.com/pkgs/misc/gpgkeys/anaconda.asc | gpg --dearmor > conda.gpg
    
- name: Check whether fingerprint is correct (will output an error message otherwise)
  shell: install -o root -g root -m 644 conda.gpg /usr/share/keyrings/conda-archive-keyring.gpg

- name: Add our Debian repo
  shell: echo "deb [arch=amd64 signed-by=/usr/share/keyrings/conda-archive-keyring.gpg] https://repo.anaconda.com/pkgs/misc/debrepo/conda stable main" > /etc/apt/sources.list.d/conda.list

- name: Update and upgrade apt packages
  apt:
    upgrade: yes
    update_cache: yes

- name: Install conda
  shell: apt install conda

- name: Remove installation file
  file:
    state: absent
    path: conda.gpg

- name: Source conda.sh
  shell: . /opt/conda/etc/profile.d/conda.sh && conda --version
  register: config

- name: Conda configs
  debug: var=config.stdout_lines

- name: Ensure conda is active on start up
  lineinfile:
    path: /base/dotfiles/.bashrc-shared-settings
    line: . /opt/conda/etc/profile.d/conda.sh

- name: Message to user
  debug:
    msg: |
      Please run . /opt/conda/etc/profile.d/conda.sh && conda --version