
- name: Install a list of packages
  apt:
    pkg:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common

- name: Download docker
  shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

- name: Register output
  command: apt-key fingerprint 0EBFCD88
  register: config
  
- name: Docker configs
  debug: var=config.stdout_lines

- name: Add stable repository
  shell: add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"

- name: Update and upgrade apt packages
  apt:
    upgrade: no
    update_cache: yes

- name: Installs
  shell: apt-get install docker-ce docker-ce-cli containerd.io

- name: Install a list of packages
  apt:
    pkg:
    - docker-ce
    - docker-ce-cli
    - containerd.io

- name: Add docker group
  shell: groupadd docker

- name: Add docker group
  shell: usermod -aG docker {{ lookup('env','USER') }}

- name: Add docker group
  shell: newgrp docker
   
- name: Register output
  command: docker run hello-world
  register: config_hello
  
- name: Docker configs
  debug: var=config_hello.stdout_lines

- name: Download docker compose
  shell: curl -L "https://github.com/docker/compose/releases/download/1.26.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose

- name: Chmod it 
  shell: chmod +x /usr/local/bin/docker-compose

- name: Register output
  command: docker-compose --version
  register: config
  
- name: Docker configs
  debug: var=config.stdout_lines
