---
- name: Set region
  command: gcloud config set compute/region {{ secrets.google_cloud.region }}

- name: Set zone
  command: gcloud config set compute/zone {{ secrets.google_cloud.zone }}
  register: config

- name: Set project
  command: gcloud config set project {{ secrets.google_cloud.name }}
  register: config

- name: Register configurations
  command: gcloud config list
  register: config

- name: Current configs
  debug: var=config.stdout_lines